optimizer:
  name: "adam"
  params:
    lr: 0.0005
    weight_decay: 0.008
    betas: [0.91, 0.998]
  lr_damp_pretrained: 0.1

scheduler:
  name: "multi_step_lr"
  params:
    milestones: [4, 8, 12, 16]
    gamma: 0.5

loss_fn: 
  name: "ce_loss"
  num_classes: 2
  weights: "auto"

batch_size: 2
epochs: 20

device: "cuda"

log_dir: "/home/kramasamy/Code/projects/cnn/models/unet/runs/"